# default: &default
#   adapter: sqlite3
#   encoding: unicode
#   pool: 5
#   host: localhost

development:
  adapter: sqlite3
  database: db/database.sqlite3
  pool: 5
  timeout: 5000

# test: &test
#   <<: *default
#     adapter: sqlite3
#   database: db/test-database.sqlite3

# production:
